### ISSUE TITLE
Is the target Java version for this project Java 8?

### ISSUE THREAD

**Issue by kmecpp** [lucko/bytesocks#2]
I see in the [pom](https://github.com/lucko/bytesocks/blob/master/pom.xml#L15) that the target Java version is Java 8.

`javap -v BytesocksClientImpl.class` shows `major version: 55` which corresponds to Java 11.

This is causing the class to fail to load on my server and breaking Spark.

Is this project somehow being compiled with JDK 11?

**Comment by lucko** [comment]
I think you are looking at the wrong repo: https://github.com/lucko/bytesocks-java-client

Yes the min version of the client is Java 11

**Comment by kmecpp** [comment]
I see. Is it possible to switch the client to Java 8 since Spark (which I believe is the only dependent plugin) is on Java 8?

**Comment by lucko** [comment]
No because it uses the java websocket API which was introduced in J11

**Comment by kmecpp** [comment]
What about make bytesocks-java-client optional for spark?

**Comment by lucko** [comment]
It already is

**Comment by kmecpp** [comment]
Ah I see. This is the exception I get on the server when I try to run the latest version of Spark

```

[01:14:38 ERROR]: Error occurred while enabling spark v1.10.34 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/spark/lib/bytesocks/BytesocksClientImpl
        at me.lucko.spark.lib.bytesocks.BytesocksClientFactory.<clinit>(BytesocksClientFactory.java:33) ~[?:?]
        at me.lucko.spark.common.SparkPlatform.<init>(SparkPlatform.java:130) ~[?:?]
        at me.lucko.spark.bukkit.BukkitSparkPlugin.onEnable(BukkitSparkPlugin.java:68) ~[?:?]
        ...
```

Looks like also catching [NoClassDefFoundError](https://github.com/lucko/bytesocks-java-client/blob/main/bytesocks-java-client/src/main/java/me/lucko/bytesocks/client/BytesocksClientFactory.java#L34) should fix the problem
